export enum NotificationType {
  ISSUE_CREATED = 'ISSUE_CREATED',
  ISSUE_ASSIGNED = 'ISSUE_ASSIGNED',
  ISSUE_COMMENTED = 'ISSUE_COMMENTED',
  ISSUE_MENTIONED = 'ISSUE_MENTIONED',
  ISSUE_STATUS_CHANGED = 'ISSUE_STATUS_CHANGED',
  ISSUE_DUE_DATE_REMINDER = 'ISSUE_DUE_DATE_REMINDER',

  PROJECT_MEMBER_ADDED = 'PROJECT_MEMBER_ADDED',
  PROJECT_ROLE_CHANGED = 'PROJECT_ROLE_CHANGED',

  SPRINT_STARTED = 'SPRINT_STARTED',
  SPRINT_COMPLETED = 'SPRINT_COMPLETED',

  WORKSPACE_INVITE = 'WORKSPACE_INVITE',

  MEETING_SCHEDULED = 'MEETING_SCHEDULED',
  MEETING_RESCHEDULED = 'MEETING_RESCHEDULED',
  MEETING_REMINDER = 'MEETING_REMINDER',

  NEW_MESSAGE = 'NEW_MESSAGE',

  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  LOGIN_FROM_NEW_DEVICE = 'LOGIN_FROM_NEW_DEVICE',

  ANNOUNCEMENT = 'ANNOUNCEMENT',
}
