import { Request } from 'express';

export enum ProjectRole {
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  BACKEND_DEVELOPER = 'BACKEND_DEVELOPER',
  FRONTEND_DEVELOPER = 'FRONTEND_DEVELOPER',
  UI_UX_DESIGNER = 'UI_UX_DESIGNER',
}

export enum Permission {
  CREATE_TASK = 'CREATE_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
  DELETE_TASK = 'DELETE_TASK',
  MANAGE_MEMBERS = 'MANAGE_MEMBERS',
  VIEW_PROJECT = 'VIEW_PROJECT',
  CREATE_EPIC = 'CREATE_EPIC',
  CREATE_SPRINT = 'CREATE_SPRINT',
  COMPLETE_SPRINT = 'COMPLETE_SPRINT',
  ASSIGN_TASK = 'ASSIGN_TASK',
  INVITE_MEMBER = 'INVITE_MEMBER',
  REMOVE_MEMBER = 'REMOVE_MEMBER',
}
