import { Request } from 'express';

export enum ProjectRole {
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  BACKEND_DEVELOPER = 'BACKEND_DEVELOPER',
  FRONTEND_DEVELOPER = 'FRONTEND_DEVELOPER',
  UI_UX_DESIGNER = 'UI_UX_DESIGNER',
}

export enum Permission {
  CREATE_TASK = 'CREATE_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
  DELETE_TASK = 'DELETE_TASK',
  MANAGE_MEMBERS = 'MANAGE_MEMBERS',
  VIEW_PROJECT = 'VIEW_PROJECT',
}
