services:
  app:
    image: sanittajohnson/planix-backend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: mongodb+srv://sanusanittasanu_db_user:b4hpcnYSYWFLSJhc@cluster0.acbdyq1.mongodb.net/
    depends_on:
      - redis

  redis:
    image: redis:latest
  mongo:
    image: mongo:latest