import { PaymentDto } from 'src/payment/dto/PaymentDto';

export const generateInvoiceHTML = (payments: PaymentDto[]) => {
  const total = payments.reduce((sum, p) => sum + p.amount, 0);

  return `
  <!DOCTYPE html>
  <html>
  <head>
    <style>
      body {
        font-family: Arial, sans-serif;
        padding: 40px;
        color: #333;
      }
      .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
      }
      .logo {
        font-size: 20px;
        font-weight: bold;
      }
      .title {
        font-size: 24px;
        font-weight: bold;
      }
      table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 30px;
      }
      th {
        text-align: left;
        padding: 10px;
        border-bottom: 2px solid #ddd;
      }
      td {
        padding: 10px;
        border-bottom: 1px solid #eee;
      }
      .total {
        text-align: right;
        margin-top: 20px;
        font-size: 16px;
        font-weight: bold;
      }
      .footer {
        margin-top: 40px;
        font-size: 12px;
        color: #777;
        text-align: center;
      }
    </style>
  </head>

  <body>
    <div class="header">
      <div class="logo"> PLANIX</div>
      <div class="title">Payments Invoice</div>
    </div>

    <table>
      <thead>
        <tr>
          <th>User</th>
          <th>Plan</th>
          <th>Amount</th>
          <th>Status</th>
          <th>Date</th>
        </tr>
      </thead>

      <tbody>
        ${payments
          .map(
            (p) => `
          <tr>
            <td>${p.user}</td>
            <td>${p.plan}</td>
            <td>₹${p.amount}</td>
            <td>${p.status}</td>
            <td>${new Date(p.startDate).toLocaleDateString('en-IN')}</td>
          </tr>
        `,
          )
          .join('')}
      </tbody>
    </table>

    <div class="total">
      Total: ₹${total}
    </div>

    <div class="footer">
      Generated by planiX • ${new Date().toLocaleDateString()}
    </div>
  </body>
  </html>
  `;
};
